from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from datetime import datetime, timezone

class DiscoveryProtocol(str, Enum):
    ARP = "ARP"
    ICMP = "ICMP"
    TCP_SYN = "TCP_SYN"
    SNMP_BRIDGE = "SNMP_BRIDGE"
    CIP_BACKPLANE = "CIP_BACKPLANE"
    PROFINET_DCP = "PROFINET_DCP"
    S7COMM_SZL = "S7COMM_SZL"
    MODBUS_FC43 = "MODBUS_FC43"
    BACNET_WHOIS = "BACNET_WHOIS"
    HOST_SOCKET = "HOST_SOCKET"
    NETFLOW_SFLOW = "NETFLOW_SFLOW"

class DiscoveryNodeMetadata(BaseModel):
    probe_id: str
    probe_type: str = "OTbase Network Discovery Node"  # or "Discovery Agent", "Discovery Proxy"
    version: str = "3.4.0"
    location_id: str
    location_path: str = "Enterprise/Site/Building/Control Room/Cabinet"
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    probed_subnets: List[str] = Field(default_factory=list)

class ArpDiscoveryEntry(BaseModel):
    ip_address: str
    mac_address: str
    oui_vendor: Optional[str] = None
    interface_name: str = "eth0"
    is_responsive: bool = True
    hostname: Optional[str] = None

class SwitchPortLearnedMac(BaseModel):
    mac_address: str
    vlan_id: int = 1
    status: str = "learned"  # learned, static, mgmt

class SwitchPortDiscovery(BaseModel):
    switch_ip: str
    switch_mac: Optional[str] = None
    switch_name: Optional[str] = None
    if_index: int
    if_name: str  # e.g. "FastEthernet0/1", "GigabitEthernet1/0/24"
    if_descr: Optional[str] = None
    if_alias: Optional[str] = None
    if_speed_bps: int = 100000000
    if_oper_status: str = "up"  # up, down
    if_admin_status: str = "up"
    duplex: str = "full"
    is_trunk: bool = False
    vlan_ids: List[int] = Field(default_factory=lambda: [1])
    learned_macs: List[SwitchPortLearnedMac] = Field(default_factory=list)
    neighbor_chassis_id: Optional[str] = None
    neighbor_port_id: Optional[str] = None
    neighbor_system_name: Optional[str] = None

class BackplaneModuleDiscovery(BaseModel):
    slot: int
    name: str
    catalog_number: str
    serial_number: Optional[str] = None
    hardware_revision: Optional[str] = None
    firmware_version: Optional[str] = None
    vendor: str = "Rockwell Automation"
    module_type: str = "Controller / CPU"
    sub_modules: List[Dict[str, Any]] = Field(default_factory=list)
    downstream_fieldbuses: List[Dict[str, Any]] = Field(default_factory=list)

class BackplaneCrawlPayload(BaseModel):
    chassis_ip: str
    chassis_model: str = "1756-A10 10-Slot ControlLogix Chassis"
    chassis_serial: Optional[str] = None
    total_slots: int = 10
    modules: List[BackplaneModuleDiscovery] = Field(default_factory=list)

class HostSocketRecord(BaseModel):
    process_name: str
    pid: Optional[int] = None
    local_ip: str
    local_port: int
    remote_ip: str
    remote_port: int
    protocol: str = "TCP"
    state: str = "ESTABLISHED"

class FlowTelemetryRecord(BaseModel):
    src_ip: str
    dst_ip: str
    src_port: int
    dst_port: int
    protocol: str = "TCP"
    byte_count: int
    packet_count: int
    sampling_ratio: int = 128
    first_switched: Optional[str] = None
    last_switched: Optional[str] = None

class PIDPayload(BaseModel):
    """
    Portable Inventory Data (PID) Schema.
    Standardized payload format generated by OTbase Discovery nodes, proxies, and agents
    and pushed via HTTPS REST API into OTbase Inventory.
    """
    pid_version: str = "1.0.0"
    metadata: DiscoveryNodeMetadata
    arp_entries: List[ArpDiscoveryEntry] = Field(default_factory=list)
    switch_ports: List[SwitchPortDiscovery] = Field(default_factory=list)
    backplane_crawls: List[BackplaneCrawlPayload] = Field(default_factory=list)
    host_sockets: List[HostSocketRecord] = Field(default_factory=list)
    flow_telemetry: List[FlowTelemetryRecord] = Field(default_factory=list)
    discovered_assets: List[Dict[str, Any]] = Field(default_factory=list)
